---
abstract: 'Interface to the OReilly Media Store.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTTP::Request: 1.40
  LWP::UserAgent: 2.33
  Readonly: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-OReillyMedia-Store
provides:
  WWW::OReillyMedia::Store:
    file: lib/WWW/OReillyMedia/Store.pm
    version: 0.03
  WWW::OReillyMedia::Store::Book:
    file: lib/WWW/OReillyMedia/Store/Book.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
